### ISSUE TITLE
Is it possible to add tiered gift?

### ISSUE THREAD

**Issue by pcook2** [nickwesselman/build-with-us-free-gift#1]
Hi,

I'm very interesetd in this repository as it is quite similar what we'd like to do for the current site.
https://evelom.com

Now, it automatically adds a free gift product to the cart in the Checkout page by custom javascript code included into **checkout.liquid**. But we have to upgrade to the new way of Checkout extensibility using Shopify Functions.

I'd like to know if it is possible to automatically add a gift product to the cart using this app.
If total_price >= 100, gift1 is added.
And customer adds more products. if total_price >= 200, gift1 is removed and gift2 is added automatically and so on.
Only one gift is added if there is a matched rule. (based on the total price)

Thank you,
Paul

**Comment by nickwesselman** [comment]
Hi @pcook2 -- Sounds possible, you'd need to manage all the product add/remove through the UI extension however. Functions can't add or remove products.
